DROP TABLE IF EXISTS jogo;

DROP TABLE IF EXISTS fase;

DROP TABLE IF EXISTS modalidade;

DROP TABLE IF EXISTS tipo;

DROP TABLE IF EXISTS time;

DROP TABLE IF EXISTS situacao;

CREATE TABLE situacao (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  nome VARCHAR(20)  NULL    ,
PRIMARY KEY(id));



CREATE TABLE time (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  nome VARCHAR(100)  NULL    ,
PRIMARY KEY(id));



CREATE TABLE tipo (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  nome VARCHAR(30)  NULL    ,
PRIMARY KEY(id));



CREATE TABLE modalidade (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  nome VARCHAR(100)  NULL    ,
PRIMARY KEY(id));



CREATE TABLE fase (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  modalidade_id INTEGER UNSIGNED  NOT NULL  ,
  nome VARCHAR(100)  NULL  ,
  tipo_id INTEGER UNSIGNED  NOT NULL    ,
PRIMARY KEY(id)  ,
  FOREIGN KEY(modalidade_id) REFERENCES modalidade(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY(tipo_id) REFERENCES tipo(id) ON DELETE NO ACTION ON UPDATE NO ACTION);



CREATE TABLE jogo (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  fase_id INTEGER UNSIGNED  NOT NULL  ,
  situacao_id INTEGER UNSIGNED  NOT NULL  ,
  ordem INTEGER UNSIGNED  NULL  ,
  time_1 INTEGER UNSIGNED  NULL  ,
  placar_1 INTEGER UNSIGNED  NULL  ,
  penalti_1 INTEGER UNSIGNED  NULL  ,
  time_2 INTEGER UNSIGNED  NULL  ,
  placar_2 INTEGER UNSIGNED  NULL  ,
  penalti_2 INTEGER UNSIGNED  NULL    ,
PRIMARY KEY(id)  ,
FOREIGN KEY(fase_id)  REFERENCES fase(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(time_1) REFERENCES time(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(time_2) REFERENCES time(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(situacao_id) REFERENCES situacao(id) ON DELETE NO ACTION ON UPDATE NO ACTION);



