DROP TABLE IF EXISTS cg_jogo;

DROP TABLE IF EXISTS cg_fase;

DROP TABLE IF EXISTS cg_modalidade;

DROP TABLE IF EXISTS cg_tipo;

DROP TABLE IF EXISTS cg_time;

DROP TABLE IF EXISTS cg_situacao;

CREATE TABLE cg_situacao (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  nome VARCHAR(20)  NULL    ,
PRIMARY KEY(id));



CREATE TABLE cg_time (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  nome VARCHAR(100)  NULL    ,
PRIMARY KEY(id));



CREATE TABLE cg_tipo (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  nome VARCHAR(30)  NULL    ,
PRIMARY KEY(id));



CREATE TABLE cg_modalidade (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  nome VARCHAR(100)  NULL    ,
PRIMARY KEY(id));



CREATE TABLE cg_fase (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  modalidade_id INTEGER UNSIGNED  NOT NULL  ,
  nome VARCHAR(100)  NULL  ,
  tipo_id INTEGER UNSIGNED  NOT NULL    ,
PRIMARY KEY(id)  ,
  FOREIGN KEY(modalidade_id) REFERENCES cg_modalidade(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY(tipo_id) REFERENCES cg_tipo(id) ON DELETE NO ACTION ON UPDATE NO ACTION);



CREATE TABLE cg_jogo (
  id INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
  fase_id INTEGER UNSIGNED  NOT NULL  ,
  situacao_id INTEGER UNSIGNED  NOT NULL  ,
  ordem INTEGER UNSIGNED  NULL  ,
  time_1 INTEGER UNSIGNED  NULL  ,
  placar_1 INTEGER UNSIGNED  NULL  ,
  penalti_1 INTEGER UNSIGNED  NULL  ,
  time_2 INTEGER UNSIGNED  NULL  ,
  placar_2 INTEGER UNSIGNED  NULL  ,
  penalti_2 INTEGER UNSIGNED  NULL    ,
PRIMARY KEY(id)  ,
FOREIGN KEY(fase_id)  REFERENCES cg_fase(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(time_1) REFERENCES cg_time(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(time_2) REFERENCES cg_time(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(situacao_id) REFERENCES cg_situacao(id) ON DELETE NO ACTION ON UPDATE NO ACTION);



